#pragma once
#include <Arduino.h>

// GENERATED by tools/gen_icons.py — edit the drawings there, not here.
// Icons: 6x6 artwork centered in an 8x8 cell (1-pixel empty border).
// One byte per row (top to bottom); bit 7 = leftmost column.
namespace icons {

using Icon = uint8_t[8];

// Round dial outline (used by the dynamic clock icons).
constexpr Icon DIAL_RING = {
  0b00000000,
  0b00111100,
  0b01000010,
  0b01000010,
  0b01000010,
  0b01000010,
  0b00111100,
  0b00000000,
};

// Static clock face with hands.
constexpr Icon CLOCK = {
  0b00000000,
  0b00111100,
  0b01010010,
  0b01010010,
  0b01011010,
  0b01000010,
  0b00111100,
  0b00000000,
};

// Calendar page; the 'today' mark blinks.
constexpr Icon CALENDAR = {
  0b00000000,
  0b00100100,
  0b01111110,
  0b01000010,
  0b01011010,
  0b01000010,
  0b01111110,
  0b00000000,
};

constexpr Icon CALENDAR_B = {
  0b00000000,
  0b00100100,
  0b01111110,
  0b01000010,
  0b01000010,
  0b01000010,
  0b01111110,
  0b00000000,
};

// Envelope: closed / opening.
constexpr Icon ENVELOPE = {
  0b00000000,
  0b01111110,
  0b01100110,
  0b01011010,
  0b01000010,
  0b01000010,
  0b01111110,
  0b00000000,
};

constexpr Icon ENVELOPE_B = {
  0b00000000,
  0b00011000,
  0b00100100,
  0b01111110,
  0b01000010,
  0b01000010,
  0b01111110,
  0b00000000,
};

// Bell swinging (alarm).
constexpr Icon BELL_L = {
  0b00000000,
  0b00010000,
  0b00111000,
  0b00111000,
  0b00111000,
  0b01111100,
  0b00010000,
  0b00000000,
};

constexpr Icon BELL_R = {
  0b00000000,
  0b00001000,
  0b00011100,
  0b00011100,
  0b00011100,
  0b00111110,
  0b00001000,
  0b00000000,
};

// Wi-Fi: arcs growing.
constexpr Icon WIFI = {
  0b00000000,
  0b00111100,
  0b01000010,
  0b00011000,
  0b00100100,
  0b00000000,
  0b00011000,
  0b00000000,
};

constexpr Icon WIFI_1 = {
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00011000,
  0b00000000,
};

constexpr Icon WIFI_2 = {
  0b00000000,
  0b00000000,
  0b00000000,
  0b00011000,
  0b00100100,
  0b00000000,
  0b00011000,
  0b00000000,
};

// No internet: Wi-Fi crossed out.
constexpr Icon WIFI_OFF = {
  0b00000000,
  0b01111100,
  0b01100010,
  0b00011000,
  0b00101100,
  0b00000100,
  0b00011010,
  0b00000000,
};

// Musical note, bouncing.
constexpr Icon NOTE = {
  0b00000000,
  0b00001100,
  0b00001010,
  0b00001000,
  0b00001000,
  0b00111000,
  0b00111000,
  0b00000000,
};

constexpr Icon NOTE_B = {
  0b00000000,
  0b00001100,
  0b00001010,
  0b00001000,
  0b00111000,
  0b00111000,
  0b00000000,
  0b00000000,
};

// Emergency: warning triangle (blinks).
constexpr Icon ALERT = {
  0b00000000,
  0b00011000,
  0b00100100,
  0b00100100,
  0b01100110,
  0b01111110,
  0b01100110,
  0b00000000,
};

constexpr Icon BLANK = {
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
};

// Gear (settings).
constexpr Icon GEAR = {
  0b00000000,
  0b00100100,
  0b00111100,
  0b01100110,
  0b01100110,
  0b00111100,
  0b00100100,
  0b00000000,
};

// Sun with rotating rays (clear day, UV).
constexpr Icon SUN = {
  0b00000000,
  0b01011010,
  0b00111100,
  0b01111110,
  0b01111110,
  0b00111100,
  0b01011010,
  0b00000000,
};

constexpr Icon SUN_B = {
  0b00000000,
  0b00100100,
  0b01011010,
  0b00111100,
  0b00111100,
  0b01011010,
  0b00100100,
  0b00000000,
};

// Moon with a twinkling star (clear night).
constexpr Icon MOON = {
  0b00000000,
  0b00011100,
  0b00110000,
  0b01100100,
  0b01100000,
  0b00110000,
  0b00011100,
  0b00000000,
};

constexpr Icon MOON_B = {
  0b00000000,
  0b00011100,
  0b00110000,
  0b01100000,
  0b01100000,
  0b00110010,
  0b00011100,
  0b00000000,
};

// Partly cloudy: sun rays blink behind the cloud.
constexpr Icon PARTLY = {
  0b00000000,
  0b01000100,
  0b00001110,
  0b00110100,
  0b01111000,
  0b01111110,
  0b00000000,
  0b00000000,
};

constexpr Icon PARTLY_B = {
  0b00000000,
  0b00000000,
  0b00001110,
  0b00110100,
  0b01111010,
  0b01111110,
  0b00000000,
  0b00000000,
};

// Cloud drifting.
constexpr Icon CLOUD = {
  0b00000000,
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111100,
  0b01111100,
  0b00000000,
  0b00000000,
};

constexpr Icon CLOUD_B = {
  0b00000000,
  0b00000000,
  0b00001100,
  0b00011110,
  0b00111110,
  0b00111110,
  0b00000000,
  0b00000000,
};

// Rain falling (3 frames).
constexpr Icon RAIN = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b01000100,
  0b00010000,
  0b00000100,
  0b00000000,
};

constexpr Icon RAIN_B = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00100010,
  0b01000100,
  0b00010000,
  0b00000000,
};

constexpr Icon RAIN_C = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00010000,
  0b00100010,
  0b01000100,
  0b00000000,
};

// Thunderstorm: lightning flashes.
constexpr Icon STORM = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00001000,
  0b00010000,
  0b00100000,
  0b00000000,
};

constexpr Icon STORM_B = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00000000,
  0b00000000,
  0b00000000,
  0b00000000,
};

// Fog drifting.
constexpr Icon FOG = {
  0b00000000,
  0b00000000,
  0b01111100,
  0b00000000,
  0b00111110,
  0b00000000,
  0b01111100,
  0b00000000,
};

constexpr Icon FOG_B = {
  0b00000000,
  0b00000000,
  0b00111110,
  0b00000000,
  0b01111100,
  0b00000000,
  0b00111110,
  0b00000000,
};

// Umbrella with drops falling.
constexpr Icon UMBRELLA = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b01001000,
  0b00001010,
  0b00011000,
  0b00000000,
};

constexpr Icon UMBRELLA_B = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00001010,
  0b01001000,
  0b00011000,
  0b00000000,
};

// Sunrise: arrow rising.
constexpr Icon SUNRISE = {
  0b00000000,
  0b00011000,
  0b00100100,
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00000000,
};

constexpr Icon SUNRISE_B = {
  0b00000000,
  0b00100100,
  0b00000000,
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00000000,
};

// Sunset: arrow sinking.
constexpr Icon SUNSET = {
  0b00000000,
  0b00100100,
  0b00011000,
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00000000,
};

constexpr Icon SUNSET_B = {
  0b00000000,
  0b00000000,
  0b00100100,
  0b00011000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00000000,
};

// Currencies and crypto.
constexpr Icon DOLLAR = {
  0b00000000,
  0b00010000,
  0b00111100,
  0b01010000,
  0b00111000,
  0b00010100,
  0b01111000,
  0b00000000,
};

constexpr Icon EURO = {
  0b00000000,
  0b00011110,
  0b00100000,
  0b01111000,
  0b00100000,
  0b01111000,
  0b00011110,
  0b00000000,
};

constexpr Icon POUND = {
  0b00000000,
  0b00011000,
  0b00100100,
  0b00100000,
  0b01111000,
  0b00100000,
  0b01111110,
  0b00000000,
};

constexpr Icon BITCOIN = {
  0b00000000,
  0b00101000,
  0b01111100,
  0b00100010,
  0b00111100,
  0b00100010,
  0b01111100,
  0b00000000,
};

constexpr Icon ETHER = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00000000,
  0b00111100,
  0b00011000,
  0b00000000,
};

// Daily change: arrow bouncing up / down.
constexpr Icon ARROW_UP = {
  0b00000000,
  0b00011000,
  0b00111100,
  0b01111110,
  0b00011000,
  0b00011000,
  0b00011000,
  0b00000000,
};

constexpr Icon ARROW_UP_B = {
  0b00000000,
  0b00111100,
  0b01111110,
  0b00011000,
  0b00011000,
  0b00011000,
  0b00000000,
  0b00000000,
};

constexpr Icon ARROW_DOWN = {
  0b00000000,
  0b00011000,
  0b00011000,
  0b00011000,
  0b01111110,
  0b00111100,
  0b00011000,
  0b00000000,
};

constexpr Icon ARROW_DOWN_B = {
  0b00000000,
  0b00000000,
  0b00011000,
  0b00011000,
  0b00011000,
  0b01111110,
  0b00111100,
  0b00000000,
};

// Animated icons: a list of frames and the time each frame stays.
struct Anim {
  const uint8_t* const* frames;
  uint8_t count;
  uint16_t periodMs;
};

static const uint8_t* const A_CALENDAR_FRAMES[] = {CALENDAR, CALENDAR_B};
constexpr Anim A_CALENDAR = {A_CALENDAR_FRAMES, 2, 600};
static const uint8_t* const A_ENVELOPE_FRAMES[] = {ENVELOPE, ENVELOPE_B};
constexpr Anim A_ENVELOPE = {A_ENVELOPE_FRAMES, 2, 500};
static const uint8_t* const A_BELL_FRAMES[] = {BELL_L, BELL_R};
constexpr Anim A_BELL = {A_BELL_FRAMES, 2, 250};
static const uint8_t* const A_WIFI_FRAMES[] = {WIFI_1, WIFI_2, WIFI};
constexpr Anim A_WIFI = {A_WIFI_FRAMES, 3, 400};
static const uint8_t* const A_NOTE_FRAMES[] = {NOTE, NOTE_B};
constexpr Anim A_NOTE = {A_NOTE_FRAMES, 2, 350};
static const uint8_t* const A_SUN_FRAMES[] = {SUN, SUN_B};
constexpr Anim A_SUN = {A_SUN_FRAMES, 2, 500};
static const uint8_t* const A_MOON_FRAMES[] = {MOON, MOON_B};
constexpr Anim A_MOON = {A_MOON_FRAMES, 2, 700};
static const uint8_t* const A_PARTLY_FRAMES[] = {PARTLY, PARTLY_B};
constexpr Anim A_PARTLY = {A_PARTLY_FRAMES, 2, 600};
static const uint8_t* const A_CLOUD_FRAMES[] = {CLOUD, CLOUD_B};
constexpr Anim A_CLOUD = {A_CLOUD_FRAMES, 2, 900};
static const uint8_t* const A_RAIN_FRAMES[] = {RAIN, RAIN_B, RAIN_C};
constexpr Anim A_RAIN = {A_RAIN_FRAMES, 3, 250};
static const uint8_t* const A_STORM_FRAMES[] = {STORM, STORM_B, STORM, STORM_B, STORM_B, STORM_B};
constexpr Anim A_STORM = {A_STORM_FRAMES, 6, 150};
static const uint8_t* const A_FOG_FRAMES[] = {FOG, FOG_B};
constexpr Anim A_FOG = {A_FOG_FRAMES, 2, 800};
static const uint8_t* const A_UMBRELLA_FRAMES[] = {UMBRELLA, UMBRELLA_B};
constexpr Anim A_UMBRELLA = {A_UMBRELLA_FRAMES, 2, 350};
static const uint8_t* const A_SUNRISE_FRAMES[] = {SUNRISE, SUNRISE_B};
constexpr Anim A_SUNRISE = {A_SUNRISE_FRAMES, 2, 400};
static const uint8_t* const A_SUNSET_FRAMES[] = {SUNSET, SUNSET_B};
constexpr Anim A_SUNSET = {A_SUNSET_FRAMES, 2, 400};
static const uint8_t* const A_ALERT_FRAMES[] = {ALERT, BLANK};
constexpr Anim A_ALERT = {A_ALERT_FRAMES, 2, 300};
static const uint8_t* const A_UP_FRAMES[] = {ARROW_UP, ARROW_UP_B};
constexpr Anim A_UP = {A_UP_FRAMES, 2, 300};
static const uint8_t* const A_DOWN_FRAMES[] = {ARROW_DOWN, ARROW_DOWN_B};
constexpr Anim A_DOWN = {A_DOWN_FRAMES, 2, 300};

// Current frame of an animation (first frame when animations are off).
inline const uint8_t* frame(const Anim& a, bool animate) {
  if (!animate || a.count < 2) return a.frames[0];
  return a.frames[(millis() / a.periodMs) % a.count];
}

}  // namespace icons
