; esp32c3-clock — firmware do relógio de mesa
; Placa: ESP32-C3 SuperMini (compatível com esp32-c3-devkitm-1)

[env:supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

; A SuperMini usa a USB nativa do C3 (sem chip conversor):
; estas flags fazem o Serial sair pela USB-C.
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    majicdesigns/MD_Parola @ ^3.7.3
    majicdesigns/MD_MAX72XX @ ^3.5.1
    mathertel/OneButton @ ^2.6.1
    tzapu/WiFiManager @ ^2.0.17
